// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<MlsSpike> createGroup() => RustLib.instance.api.crateApiMlsCreateGroup();

Future<bool> addMember({required MlsSpike spike}) =>
    RustLib.instance.api.crateApiMlsAddMember(spike: spike);

Future<bool> removeMemberAndVerify({required MlsSpike spike}) =>
    RustLib.instance.api.crateApiMlsRemoveMemberAndVerify(spike: spike);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MlsSpike>>
abstract class MlsSpike implements RustOpaqueInterface {}
