// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'ledger.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `lock`, `next_timestamp`, `period_label`, `resolve`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `BudgetBookData`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `eq`, `fmt`

/// Opens a budget book by replaying a durable log's bytes. Pass an empty
/// `log_bytes` for a brand-new installation; matches
/// `ledger::load_personal_ledger`/`categories::load_category_book`.
Future<BudgetBook> loadBudgetBook({
  required String actorId,
  required List<int> logBytes,
}) => RustLib.instance.api.crateApiBudgetsLoadBudgetBook(
  actorId: actorId,
  logBytes: logBytes,
);

Future<BudgetLoadReport> budgetLoadReport({required BudgetBook book}) =>
    RustLib.instance.api.crateApiBudgetsBudgetLoadReport(book: book);

/// Creates or updates a budget. `limit_amount`/`limit_currency_code` must use
/// the ledger's reporting currency: budget progress is always computed and
/// displayed in that currency (see `budget_progress`), so a mismatched
/// currency here would silently compare unlike units.
Future<BudgetMutation> upsertBudget({
  required BudgetBook book,
  required String budgetId,
  required String name,
  String? categoryId,
  required String limitAmount,
  required String limitCurrencyCode,
  required BudgetPeriodKind period,
  int? customPeriodDays,
  required PlatformInt64 wallClockMillis,
}) => RustLib.instance.api.crateApiBudgetsUpsertBudget(
  book: book,
  budgetId: budgetId,
  name: name,
  categoryId: categoryId,
  limitAmount: limitAmount,
  limitCurrencyCode: limitCurrencyCode,
  period: period,
  customPeriodDays: customPeriodDays,
  wallClockMillis: wallClockMillis,
);

/// Every budget's current progress, computed against `now_millis` (the
/// caller's wall clock — this crate has no wall-clock dependency of its own).
Future<List<BudgetView>> budgetProgress({
  required PersonalLedger ledger,
  required BudgetBook book,
  required PlatformInt64 nowMillis,
}) => RustLib.instance.api.crateApiBudgetsBudgetProgress(
  ledger: ledger,
  book: book,
  nowMillis: nowMillis,
);

/// Append a lifecycle tombstone; past ledger transactions are unchanged.
/// Validate the current fold before advancing the clock.
Future<BudgetMutation> removeBudget({
  required BudgetBook book,
  required String budgetId,
  required PlatformInt64 wallClockMillis,
}) => RustLib.instance.api.crateApiBudgetsRemoveBudget(
  book: book,
  budgetId: budgetId,
  wallClockMillis: wallClockMillis,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BudgetBook>>
abstract class BudgetBook implements RustOpaqueInterface {}

class BudgetLoadReport {
  final BigInt recoveredUpsertCount;
  final BigInt truncatedBytes;

  const BudgetLoadReport({
    required this.recoveredUpsertCount,
    required this.truncatedBytes,
  });

  @override
  int get hashCode => recoveredUpsertCount.hashCode ^ truncatedBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BudgetLoadReport &&
          runtimeType == other.runtimeType &&
          recoveredUpsertCount == other.recoveredUpsertCount &&
          truncatedBytes == other.truncatedBytes;
}

class BudgetMutation {
  final Uint8List appendedFrame;

  const BudgetMutation({required this.appendedFrame});

  @override
  int get hashCode => appendedFrame.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BudgetMutation &&
          runtimeType == other.runtimeType &&
          appendedFrame == other.appendedFrame;
}

/// Mirrors `cash_core::BudgetPeriod` as a bridge-visible type. Kept
/// field-less (unlike the core type's `Custom { days }`) with the day count
/// passed alongside as its own parameter in `upsert_budget`: a data-carrying
/// enum here would need `flutter_rust_bridge` to generate a `freezed` union
/// type on the Dart side, pulling in a code-generation dependency this
/// project otherwise has no use for, for one field.
enum BudgetPeriodKind { weekly, monthly, yearly, custom }

/// A budget's current progress, computed fresh from the ledger's expenses in
/// its period (see module docs). `percent_used` can exceed 100 when a budget
/// is overspent; it is never negative.
class BudgetView {
  final String id;
  final String name;
  final String? categoryId;
  final String periodLabel;
  final String limitLabel;
  final String spentLabel;
  final PlatformInt64 percentUsed;

  const BudgetView({
    required this.id,
    required this.name,
    this.categoryId,
    required this.periodLabel,
    required this.limitLabel,
    required this.spentLabel,
    required this.percentUsed,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      categoryId.hashCode ^
      periodLabel.hashCode ^
      limitLabel.hashCode ^
      spentLabel.hashCode ^
      percentUsed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BudgetView &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          categoryId == other.categoryId &&
          periodLabel == other.periodLabel &&
          limitLabel == other.limitLabel &&
          spentLabel == other.spentLabel &&
          percentUsed == other.percentUsed;
}
