// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `lock`, `next_timestamp`, `views`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CategoryBookData`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `eq`, `fmt`

/// Opens a category book by replaying a durable log's bytes. Pass an empty
/// `log_bytes` for a brand-new installation; this is the only constructor,
/// so first launch and every later restart share one code path, matching
/// `ledger::load_personal_ledger`.
CategoryBook loadCategoryBook({
  required String actorId,
  required List<int> logBytes,
}) => RustLib.instance.api.crateApiCategoriesLoadCategoryBook(
  actorId: actorId,
  logBytes: logBytes,
);

/// Reports what a completed [`load_category_book`] call recovered.
CategoryLoadReport categoryLoadReport({required CategoryBook book}) =>
    RustLib.instance.api.crateApiCategoriesCategoryLoadReport(book: book);

/// Creates or updates a category's name and icon. `category_id` is a stable
/// key the caller chooses once (e.g. a slug); calling this again with the
/// same ID always upserts rather than duplicating.
CategoryMutation upsertCategory({
  required CategoryBook book,
  required String categoryId,
  required String name,
  required String iconKey,
  required PlatformInt64 wallClockMillis,
}) => RustLib.instance.api.crateApiCategoriesUpsertCategory(
  book: book,
  categoryId: categoryId,
  name: name,
  iconKey: iconKey,
  wallClockMillis: wallClockMillis,
);

List<CategoryView> listCategories({required CategoryBook book}) =>
    RustLib.instance.api.crateApiCategoriesListCategories(book: book);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CategoryBook>>
abstract class CategoryBook implements RustOpaqueInterface {}

/// Diagnostics from the load that produced a category book's current state.
class CategoryLoadReport {
  final List<CategoryView> categories;
  final BigInt recoveredUpsertCount;
  final BigInt truncatedBytes;

  const CategoryLoadReport({
    required this.categories,
    required this.recoveredUpsertCount,
    required this.truncatedBytes,
  });

  @override
  int get hashCode =>
      categories.hashCode ^
      recoveredUpsertCount.hashCode ^
      truncatedBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CategoryLoadReport &&
          runtimeType == other.runtimeType &&
          categories == other.categories &&
          recoveredUpsertCount == other.recoveredUpsertCount &&
          truncatedBytes == other.truncatedBytes;
}

/// The result of a mutation that appended one upsert. `appended_frame` is
/// the durable-log frame for that upsert; the caller (Dart) must append
/// these bytes to its durable store before treating the mutation as
/// committed, the same protocol `ledger::LedgerMutation` uses.
class CategoryMutation {
  final List<CategoryView> categories;
  final Uint8List appendedFrame;

  const CategoryMutation({
    required this.categories,
    required this.appendedFrame,
  });

  @override
  int get hashCode => categories.hashCode ^ appendedFrame.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CategoryMutation &&
          runtimeType == other.runtimeType &&
          categories == other.categories &&
          appendedFrame == other.appendedFrame;
}

class CategoryView {
  final String id;
  final String name;
  final String iconKey;

  const CategoryView({
    required this.id,
    required this.name,
    required this.iconKey,
  });

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ iconKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CategoryView &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          iconKey == other.iconKey;
}
