// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'ledger.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `lock`, `next_timestamp`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `GoalBookData`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `eq`, `fmt`, `from`

/// Opens a goal book by replaying a durable log's bytes. Pass an empty
/// `log_bytes` for a brand-new installation; matches
/// `ledger::load_personal_ledger`/`categories::load_category_book`/
/// `budgets::load_budget_book`.
GoalBook loadGoalBook({required String actorId, required List<int> logBytes}) =>
    RustLib.instance.api.crateApiGoalsLoadGoalBook(
      actorId: actorId,
      logBytes: logBytes,
    );

GoalLoadReport goalLoadReport({required GoalBook book}) =>
    RustLib.instance.api.crateApiGoalsGoalLoadReport(book: book);

/// Creates or updates a goal. A save goal must name the account whose
/// balance counts toward the target and must leave `category_id` unset; a
/// spend goal must leave `linked_account_id` unset (its cap can optionally
/// be scoped to one category). `target_amount`/`target_currency_code` must
/// use the same currency as whatever the goal is measured against (the
/// linked account for a save goal, the ledger's reporting currency for a
/// spend goal) — see `goal_progress` and `docs/DECISIONS.md`.
GoalMutation upsertGoal({
  required GoalBook book,
  required String goalId,
  required String name,
  required GoalKind kind,
  required String targetAmount,
  required String targetCurrencyCode,
  String? linkedAccountId,
  String? categoryId,
  PlatformInt64? deadlineMillis,
  required PlatformInt64 wallClockMillis,
}) => RustLib.instance.api.crateApiGoalsUpsertGoal(
  book: book,
  goalId: goalId,
  name: name,
  kind: kind,
  targetAmount: targetAmount,
  targetCurrencyCode: targetCurrencyCode,
  linkedAccountId: linkedAccountId,
  categoryId: categoryId,
  deadlineMillis: deadlineMillis,
  wallClockMillis: wallClockMillis,
);

/// Every goal's current progress. A save goal's progress is its linked
/// account's current balance; a spend goal's progress is the total of its
/// matching (non-voided) expenses recorded since the goal was first created
/// (the earliest upsert for that `goal_id`) up to its deadline, if any. There
/// is no `now_millis` parameter (unlike `budget_progress`): a goal's window
/// starts at its own creation and never rolls forward, so nothing here
/// depends on the caller's wall clock.
List<GoalView> goalProgress({
  required PersonalLedger ledger,
  required GoalBook book,
}) =>
    RustLib.instance.api.crateApiGoalsGoalProgress(ledger: ledger, book: book);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<GoalBook>>
abstract class GoalBook implements RustOpaqueInterface {}

/// Mirrors `cash_core::GoalKind` as a bridge-visible type (kept as its own
/// type, rather than re-exporting the core enum, so `rust/core` never
/// depends on `flutter_rust_bridge`).
enum GoalKind { save, spend }

class GoalLoadReport {
  final BigInt recoveredUpsertCount;
  final BigInt truncatedBytes;

  const GoalLoadReport({
    required this.recoveredUpsertCount,
    required this.truncatedBytes,
  });

  @override
  int get hashCode => recoveredUpsertCount.hashCode ^ truncatedBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GoalLoadReport &&
          runtimeType == other.runtimeType &&
          recoveredUpsertCount == other.recoveredUpsertCount &&
          truncatedBytes == other.truncatedBytes;
}

class GoalMutation {
  final Uint8List appendedFrame;

  const GoalMutation({required this.appendedFrame});

  @override
  int get hashCode => appendedFrame.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GoalMutation &&
          runtimeType == other.runtimeType &&
          appendedFrame == other.appendedFrame;
}

/// A goal's current progress, computed fresh from the ledger (see module
/// docs). `percent_complete` can exceed 100 (over-saved, or over-spent past
/// a spending cap); it is never negative.
class GoalView {
  final String id;
  final String name;
  final bool isSave;
  final String? linkedAccountId;
  final String? categoryId;
  final String targetLabel;
  final String progressLabel;
  final PlatformInt64 percentComplete;
  final PlatformInt64? deadlineMillis;

  const GoalView({
    required this.id,
    required this.name,
    required this.isSave,
    this.linkedAccountId,
    this.categoryId,
    required this.targetLabel,
    required this.progressLabel,
    required this.percentComplete,
    this.deadlineMillis,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      isSave.hashCode ^
      linkedAccountId.hashCode ^
      categoryId.hashCode ^
      targetLabel.hashCode ^
      progressLabel.hashCode ^
      percentComplete.hashCode ^
      deadlineMillis.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GoalView &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          isSave == other.isSave &&
          linkedAccountId == other.linkedAccountId &&
          categoryId == other.categoryId &&
          targetLabel == other.targetLabel &&
          progressLabel == other.progressLabel &&
          percentComplete == other.percentComplete &&
          deadlineMillis == other.deadlineMillis;
}
