// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `active_transaction`, `append_and_mutation`, `check_expected_amount`, `folded_state`, `lock`, `next_event`, `overview_from_state`, `overview`, `reporting_balances`, `summary_view`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `LedgerData`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

/// Read-only; nothing is queued or persisted until the distinct publish call.
/// The caller must show the exact preview and target group before confirmation.
Future<SummaryDraft> prepareSummary({
  required PersonalLedger ledger,
  required String groupId,
  required PlatformInt64 startMillis,
  required PlatformInt64 endMillisExclusive,
  required bool includeIncome,
  required bool includeExpenses,
}) => RustLib.instance.api.crateApiLedgerPrepareSummary(
  ledger: ledger,
  groupId: groupId,
  startMillis: startMillis,
  endMillisExclusive: endMillisExclusive,
  includeIncome: includeIncome,
  includeExpenses: includeExpenses,
);

Future<SummaryPreview> summaryPreview({required SummaryDraft draft}) =>
    RustLib.instance.api.crateApiLedgerSummaryPreview(draft: draft);

/// Opens a personal ledger by replaying a durable log's bytes. Pass an empty
/// `log_bytes` for a brand-new installation; this is the only ledger
/// constructor, so first launch and every later restart share one code path.
/// Call [`load_report`] on the result to see what was recovered.
///
/// `actor_id` must be the same stable identifier persisted alongside the log
/// on a previous launch: it anchors this device's place in the total order,
/// and changing it after events exist would let two different actors claim
/// the same event IDs.
Future<PersonalLedger> loadPersonalLedger({
  required String actorId,
  required String reportingCurrencyCode,
  required List<int> logBytes,
}) => RustLib.instance.api.crateApiLedgerLoadPersonalLedger(
  actorId: actorId,
  reportingCurrencyCode: reportingCurrencyCode,
  logBytes: logBytes,
);

/// Reports what a completed [`load_personal_ledger`] call recovered.
Future<LoadReport> loadReport({required PersonalLedger ledger}) =>
    RustLib.instance.api.crateApiLedgerLoadReport(ledger: ledger);

Future<LedgerMutation> addAccount({
  required PersonalLedger ledger,
  required String accountId,
  required String name,
  required String currencyCode,
  required PlatformInt64 wallClockMillis,
}) => RustLib.instance.api.crateApiLedgerAddAccount(
  ledger: ledger,
  accountId: accountId,
  name: name,
  currencyCode: currencyCode,
  wallClockMillis: wallClockMillis,
);

/// Converts a user-typed decimal rate ("1.0875" target units per one source
/// unit) into the exact integer ratio the ledger freezes on an entry.
Future<FxRatio> fxRateFromDecimal({
  required String rate,
  required String sourceCurrencyCode,
  required String targetCurrencyCode,
}) => RustLib.instance.api.crateApiLedgerFxRateFromDecimal(
  rate: rate,
  sourceCurrencyCode: sourceCurrencyCode,
  targetCurrencyCode: targetCurrencyCode,
);

Future<LedgerMutation> recordTransaction({
  required PersonalLedger ledger,
  required String transactionId,
  required String accountId,
  required EntryKind kind,
  required String amount,
  required String currencyCode,
  required PlatformInt64 fxNumerator,
  required PlatformInt64 fxDenominator,
  required String title,
  String? categoryId,
  String? recurringId,
  required PlatformInt64 wallClockMillis,
}) => RustLib.instance.api.crateApiLedgerRecordTransaction(
  ledger: ledger,
  transactionId: transactionId,
  accountId: accountId,
  kind: kind,
  amount: amount,
  currencyCode: currencyCode,
  fxNumerator: fxNumerator,
  fxDenominator: fxDenominator,
  title: title,
  categoryId: categoryId,
  recurringId: recurringId,
  wallClockMillis: wallClockMillis,
);

/// Records a transfer between two of this ledger's own accounts.
/// `sent_amount`/`sent_currency_code` must match `from_account_id`'s
/// currency, and `received_amount`/`received_currency_code` must match
/// `to_account_id`'s; for a same-currency transfer these are normally equal,
/// but nothing here requires it (see `cash_core::EventKind::TransferRecorded`
/// for why a cross-currency spread stays visible rather than assumed away).
Future<LedgerMutation> recordTransfer({
  required PersonalLedger ledger,
  required String transferId,
  required String fromAccountId,
  required String toAccountId,
  required String sentAmount,
  required String sentCurrencyCode,
  required PlatformInt64 sentFxNumerator,
  required PlatformInt64 sentFxDenominator,
  required String receivedAmount,
  required String receivedCurrencyCode,
  required PlatformInt64 receivedFxNumerator,
  required PlatformInt64 receivedFxDenominator,
  required String title,
  required PlatformInt64 wallClockMillis,
}) => RustLib.instance.api.crateApiLedgerRecordTransfer(
  ledger: ledger,
  transferId: transferId,
  fromAccountId: fromAccountId,
  toAccountId: toAccountId,
  sentAmount: sentAmount,
  sentCurrencyCode: sentCurrencyCode,
  sentFxNumerator: sentFxNumerator,
  sentFxDenominator: sentFxDenominator,
  receivedAmount: receivedAmount,
  receivedCurrencyCode: receivedCurrencyCode,
  receivedFxNumerator: receivedFxNumerator,
  receivedFxDenominator: receivedFxDenominator,
  title: title,
  wallClockMillis: wallClockMillis,
);

Future<LedgerOverview> getOverview({required PersonalLedger ledger}) =>
    RustLib.instance.api.crateApiLedgerGetOverview(ledger: ledger);

/// Corrects only the amount, retaining the entry's original currency and frozen
/// exchange rate. An outdated selection is rejected instead of overwriting it.
Future<LedgerMutation> adjustTransactionAmount({
  required PersonalLedger ledger,
  required String transactionId,
  required String expectedAmount,
  required String amount,
  required PlatformInt64 wallClockMillis,
}) => RustLib.instance.api.crateApiLedgerAdjustTransactionAmount(
  ledger: ledger,
  transactionId: transactionId,
  expectedAmount: expectedAmount,
  amount: amount,
  wallClockMillis: wallClockMillis,
);

Future<LedgerMutation> assignTransactionCategory({
  required PersonalLedger ledger,
  required String transactionId,
  String? expectedCategoryId,
  String? categoryId,
  required PlatformInt64 wallClockMillis,
}) => RustLib.instance.api.crateApiLedgerAssignTransactionCategory(
  ledger: ledger,
  transactionId: transactionId,
  expectedCategoryId: expectedCategoryId,
  categoryId: categoryId,
  wallClockMillis: wallClockMillis,
);

/// Excludes the entry from balances without erasing any of its history.
Future<LedgerMutation> voidTransaction({
  required PersonalLedger ledger,
  required String transactionId,
  required String expectedAmount,
  String? expectedCategoryId,
  required PlatformInt64 wallClockMillis,
}) => RustLib.instance.api.crateApiLedgerVoidTransaction(
  ledger: ledger,
  transactionId: transactionId,
  expectedAmount: expectedAmount,
  expectedCategoryId: expectedCategoryId,
  wallClockMillis: wallClockMillis,
);

Future<List<TransactionHistoryView>> transactionHistory({
  required PersonalLedger ledger,
  required String transactionId,
}) => RustLib.instance.api.crateApiLedgerTransactionHistory(
  ledger: ledger,
  transactionId: transactionId,
);

/// "Custom titles that auto-assign on repeat" (build brief §5): the category
/// of the most recent past transaction whose title matches, trimmed and
/// case-insensitive, or `None` if nothing matches (or that transaction had
/// no category either). This is a UI convenience, not part of the ledger's
/// financial state, so it never fails the way recording a transaction can.
Future<String?> suggestCategoryForTitle({
  required PersonalLedger ledger,
  required String title,
}) => RustLib.instance.api.crateApiLedgerSuggestCategoryForTitle(
  ledger: ledger,
  title: title,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PersonalLedger>>
abstract class PersonalLedger implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SummaryDraft>>
abstract class SummaryDraft implements RustOpaqueInterface {}

class AccountView {
  final String id;
  final String name;
  final String currencyCode;
  final String balanceLabel;

  /// The account's balance valued at each entry's frozen rate, in the
  /// ledger's reporting currency. `None` for accounts already held in the
  /// reporting currency, where it would only repeat `balance_label`.
  final String? reportingBalanceLabel;

  const AccountView({
    required this.id,
    required this.name,
    required this.currencyCode,
    required this.balanceLabel,
    this.reportingBalanceLabel,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      currencyCode.hashCode ^
      balanceLabel.hashCode ^
      reportingBalanceLabel.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccountView &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          currencyCode == other.currencyCode &&
          balanceLabel == other.balanceLabel &&
          reportingBalanceLabel == other.reportingBalanceLabel;
}

enum EntryKind { expense, income }

/// An exact exchange-rate ratio, as accepted by `record_transaction` and
/// `record_transfer`: target minor units per one source minor unit.
class FxRatio {
  final PlatformInt64 numerator;
  final PlatformInt64 denominator;

  const FxRatio({required this.numerator, required this.denominator});

  @override
  int get hashCode => numerator.hashCode ^ denominator.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FxRatio &&
          runtimeType == other.runtimeType &&
          numerator == other.numerator &&
          denominator == other.denominator;
}

/// The result of a mutation that appended one event. `appended_frame` is the
/// durable-log frame for that event and only exists when the mutation
/// succeeded: a rejected write never reaches this struct, so it can never be
/// persisted. The caller (Dart) must append these bytes to its durable store
/// before treating the mutation as committed.
class LedgerMutation {
  final LedgerOverview overview;
  final Uint8List appendedFrame;

  const LedgerMutation({required this.overview, required this.appendedFrame});

  @override
  int get hashCode => overview.hashCode ^ appendedFrame.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LedgerMutation &&
          runtimeType == other.runtimeType &&
          overview == other.overview &&
          appendedFrame == other.appendedFrame;
}

class LedgerOverview {
  final String balanceLabel;
  final List<AccountView> accounts;
  final List<TransactionView> transactions;
  final List<TransferView> transfers;

  const LedgerOverview({
    required this.balanceLabel,
    required this.accounts,
    required this.transactions,
    required this.transfers,
  });

  @override
  int get hashCode =>
      balanceLabel.hashCode ^
      accounts.hashCode ^
      transactions.hashCode ^
      transfers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LedgerOverview &&
          runtimeType == other.runtimeType &&
          balanceLabel == other.balanceLabel &&
          accounts == other.accounts &&
          transactions == other.transactions &&
          transfers == other.transfers;
}

/// Diagnostics from the load that produced a ledger's current in-memory
/// state. `recovered_event_count` and `truncated_bytes` let the caller
/// distinguish a clean load from one that dropped a torn write at the tail,
/// per [`cash_core::decode_event_log`].
class LoadReport {
  final LedgerOverview overview;
  final BigInt recoveredEventCount;
  final BigInt truncatedBytes;

  const LoadReport({
    required this.overview,
    required this.recoveredEventCount,
    required this.truncatedBytes,
  });

  @override
  int get hashCode =>
      overview.hashCode ^
      recoveredEventCount.hashCode ^
      truncatedBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LoadReport &&
          runtimeType == other.runtimeType &&
          overview == other.overview &&
          recoveredEventCount == other.recoveredEventCount &&
          truncatedBytes == other.truncatedBytes;
}

class SummaryPreview {
  final String groupId;
  final String currencyCode;
  final PlatformInt64 startMillis;
  final PlatformInt64 endMillisExclusive;
  final String? incomeLabel;
  final String? expensesLabel;

  const SummaryPreview({
    required this.groupId,
    required this.currencyCode,
    required this.startMillis,
    required this.endMillisExclusive,
    this.incomeLabel,
    this.expensesLabel,
  });

  @override
  int get hashCode =>
      groupId.hashCode ^
      currencyCode.hashCode ^
      startMillis.hashCode ^
      endMillisExclusive.hashCode ^
      incomeLabel.hashCode ^
      expensesLabel.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SummaryPreview &&
          runtimeType == other.runtimeType &&
          groupId == other.groupId &&
          currencyCode == other.currencyCode &&
          startMillis == other.startMillis &&
          endMillisExclusive == other.endMillisExclusive &&
          incomeLabel == other.incomeLabel &&
          expensesLabel == other.expensesLabel;
}

/// Immutable entries in this transaction's history, in the ledger's total order.
class TransactionHistoryView {
  final String eventId;
  final String actorId;
  final PlatformInt64 physicalMillis;
  final int logical;
  final String action;
  final String? amountLabel;
  final String? reportingAmountLabel;
  final String? categoryId;

  const TransactionHistoryView({
    required this.eventId,
    required this.actorId,
    required this.physicalMillis,
    required this.logical,
    required this.action,
    this.amountLabel,
    this.reportingAmountLabel,
    this.categoryId,
  });

  @override
  int get hashCode =>
      eventId.hashCode ^
      actorId.hashCode ^
      physicalMillis.hashCode ^
      logical.hashCode ^
      action.hashCode ^
      amountLabel.hashCode ^
      reportingAmountLabel.hashCode ^
      categoryId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransactionHistoryView &&
          runtimeType == other.runtimeType &&
          eventId == other.eventId &&
          actorId == other.actorId &&
          physicalMillis == other.physicalMillis &&
          logical == other.logical &&
          action == other.action &&
          amountLabel == other.amountLabel &&
          reportingAmountLabel == other.reportingAmountLabel &&
          categoryId == other.categoryId;
}

class TransactionView {
  final String id;
  final String accountId;
  final String title;
  final String amountLabel;
  final bool isExpense;
  final String? categoryId;
  final bool voided;

  const TransactionView({
    required this.id,
    required this.accountId,
    required this.title,
    required this.amountLabel,
    required this.isExpense,
    this.categoryId,
    required this.voided,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      accountId.hashCode ^
      title.hashCode ^
      amountLabel.hashCode ^
      isExpense.hashCode ^
      categoryId.hashCode ^
      voided.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransactionView &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          accountId == other.accountId &&
          title == other.title &&
          amountLabel == other.amountLabel &&
          isExpense == other.isExpense &&
          categoryId == other.categoryId &&
          voided == other.voided;
}

class TransferView {
  final String id;
  final String title;
  final String fromAccountId;
  final String toAccountId;
  final String sentLabel;
  final String receivedLabel;

  const TransferView({
    required this.id,
    required this.title,
    required this.fromAccountId,
    required this.toAccountId,
    required this.sentLabel,
    required this.receivedLabel,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      fromAccountId.hashCode ^
      toAccountId.hashCode ^
      sentLabel.hashCode ^
      receivedLabel.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransferView &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          fromAccountId == other.fromAccountId &&
          toAccountId == other.toAccountId &&
          sentLabel == other.sentLabel &&
          receivedLabel == other.receivedLabel;
}
