// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `append_and_overview`, `lock`, `next_event`, `overview_from_state`, `overview`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `LedgerData`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

Future<PersonalLedger> createPersonalLedger({
  required String actorId,
  required String reportingCurrencyCode,
}) => RustLib.instance.api.crateApiLedgerCreatePersonalLedger(
  actorId: actorId,
  reportingCurrencyCode: reportingCurrencyCode,
);

Future<LedgerOverview> addAccount({
  required PersonalLedger ledger,
  required String accountId,
  required String name,
  required String currencyCode,
  required PlatformInt64 wallClockMillis,
}) => RustLib.instance.api.crateApiLedgerAddAccount(
  ledger: ledger,
  accountId: accountId,
  name: name,
  currencyCode: currencyCode,
  wallClockMillis: wallClockMillis,
);

Future<LedgerOverview> recordTransaction({
  required PersonalLedger ledger,
  required String transactionId,
  required String accountId,
  required EntryKind kind,
  required String amount,
  required String currencyCode,
  required PlatformInt64 fxNumerator,
  required PlatformInt64 fxDenominator,
  required String title,
  String? categoryId,
  required PlatformInt64 wallClockMillis,
}) => RustLib.instance.api.crateApiLedgerRecordTransaction(
  ledger: ledger,
  transactionId: transactionId,
  accountId: accountId,
  kind: kind,
  amount: amount,
  currencyCode: currencyCode,
  fxNumerator: fxNumerator,
  fxDenominator: fxDenominator,
  title: title,
  categoryId: categoryId,
  wallClockMillis: wallClockMillis,
);

Future<LedgerOverview> getOverview({required PersonalLedger ledger}) =>
    RustLib.instance.api.crateApiLedgerGetOverview(ledger: ledger);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PersonalLedger>>
abstract class PersonalLedger implements RustOpaqueInterface {}

class AccountView {
  final String id;
  final String name;
  final String balanceLabel;

  const AccountView({
    required this.id,
    required this.name,
    required this.balanceLabel,
  });

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ balanceLabel.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccountView &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          balanceLabel == other.balanceLabel;
}

enum EntryKind { expense, income }

class LedgerOverview {
  final String balanceLabel;
  final List<AccountView> accounts;
  final List<TransactionView> transactions;

  const LedgerOverview({
    required this.balanceLabel,
    required this.accounts,
    required this.transactions,
  });

  @override
  int get hashCode =>
      balanceLabel.hashCode ^ accounts.hashCode ^ transactions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LedgerOverview &&
          runtimeType == other.runtimeType &&
          balanceLabel == other.balanceLabel &&
          accounts == other.accounts &&
          transactions == other.transactions;
}

class TransactionView {
  final String id;
  final String title;
  final String amountLabel;
  final bool isExpense;
  final String? categoryId;

  const TransactionView({
    required this.id,
    required this.title,
    required this.amountLabel,
    required this.isExpense,
    this.categoryId,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      amountLabel.hashCode ^
      isExpense.hashCode ^
      categoryId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransactionView &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          amountLabel == other.amountLabel &&
          isExpense == other.isExpense &&
          categoryId == other.categoryId;
}
