// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'ledger.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `lock`, `next_timestamp`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `RecurringBookData`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `eq`, `eq`, `fmt`, `fmt`, `from`, `from`, `from`

/// Opens a recurring-rule book by replaying a durable log's bytes. Pass an
/// empty `log_bytes` for a brand-new installation; matches
/// `ledger::load_personal_ledger`/`budgets::load_budget_book`/
/// `goals::load_goal_book`.
Future<RecurringBook> loadRecurringBook({
  required String actorId,
  required List<int> logBytes,
}) => RustLib.instance.api.crateApiRecurringLoadRecurringBook(
  actorId: actorId,
  logBytes: logBytes,
);

Future<RecurringLoadReport> recurringLoadReport({
  required RecurringBook book,
}) => RustLib.instance.api.crateApiRecurringRecurringLoadReport(book: book);

/// Creates or updates a recurring rule. `amount`/`currency_code` must use
/// `account_id`'s own currency, exactly like `ledger::record_transaction`,
/// since recording a due occurrence calls that same function with these
/// values.
Future<RecurringMutation> upsertRecurring({
  required RecurringBook book,
  required String recurringId,
  required String title,
  required RecurringKind kind,
  required String amount,
  required String currencyCode,
  required String accountId,
  String? categoryId,
  required RecurringFrequency frequency,
  required PlatformInt64 startMillis,
  required PlatformInt64 wallClockMillis,
}) => RustLib.instance.api.crateApiRecurringUpsertRecurring(
  book: book,
  recurringId: recurringId,
  title: title,
  kind: kind,
  amount: amount,
  currencyCode: currencyCode,
  accountId: accountId,
  categoryId: categoryId,
  frequency: frequency,
  startMillis: startMillis,
  wallClockMillis: wallClockMillis,
);

/// Every rule's next occurrence at or before `now_millis + horizon_days`.
/// For each rule, the anchor is the latest ledger transaction tagged with
/// its `recurring_id` (or the rule's own `start_millis`, if none has been
/// recorded yet); the occurrence returned is the first one strictly after
/// that anchor.
Future<List<UpcomingView>> upcomingOccurrences({
  required PersonalLedger ledger,
  required RecurringBook book,
  required PlatformInt64 nowMillis,
  required int horizonDays,
}) => RustLib.instance.api.crateApiRecurringUpcomingOccurrences(
  ledger: ledger,
  book: book,
  nowMillis: nowMillis,
  horizonDays: horizonDays,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RecurringBook>>
abstract class RecurringBook implements RustOpaqueInterface {}

/// Mirrors `cash_core::RecurringFrequency`.
enum RecurringFrequency { daily, weekly, monthly, yearly }

/// Mirrors `cash_core::RecurringKind` as a bridge-visible type (kept as its
/// own type for the same reason `goals::GoalKind` is: `rust/core` never
/// depends on `flutter_rust_bridge`).
enum RecurringKind { expense, income }

class RecurringLoadReport {
  final BigInt recoveredUpsertCount;
  final BigInt truncatedBytes;

  const RecurringLoadReport({
    required this.recoveredUpsertCount,
    required this.truncatedBytes,
  });

  @override
  int get hashCode => recoveredUpsertCount.hashCode ^ truncatedBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RecurringLoadReport &&
          runtimeType == other.runtimeType &&
          recoveredUpsertCount == other.recoveredUpsertCount &&
          truncatedBytes == other.truncatedBytes;
}

class RecurringMutation {
  final Uint8List appendedFrame;

  const RecurringMutation({required this.appendedFrame});

  @override
  int get hashCode => appendedFrame.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RecurringMutation &&
          runtimeType == other.runtimeType &&
          appendedFrame == other.appendedFrame;
}

/// One recurring rule's next due occurrence, computed fresh (see module
/// docs). `is_overdue` is true when the occurrence is at or before the
/// caller's `now_millis`.
class UpcomingView {
  final String recurringId;
  final String title;
  final bool isExpense;
  final String amountLabel;
  final String accountId;
  final String? categoryId;
  final RecurringFrequency frequency;
  final PlatformInt64 occurrenceMillis;
  final bool isOverdue;

  const UpcomingView({
    required this.recurringId,
    required this.title,
    required this.isExpense,
    required this.amountLabel,
    required this.accountId,
    this.categoryId,
    required this.frequency,
    required this.occurrenceMillis,
    required this.isOverdue,
  });

  @override
  int get hashCode =>
      recurringId.hashCode ^
      title.hashCode ^
      isExpense.hashCode ^
      amountLabel.hashCode ^
      accountId.hashCode ^
      categoryId.hashCode ^
      frequency.hashCode ^
      occurrenceMillis.hashCode ^
      isOverdue.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UpcomingView &&
          runtimeType == other.runtimeType &&
          recurringId == other.recurringId &&
          title == other.title &&
          isExpense == other.isExpense &&
          amountLabel == other.amountLabel &&
          accountId == other.accountId &&
          categoryId == other.categoryId &&
          frequency == other.frequency &&
          occurrenceMillis == other.occurrenceMillis &&
          isOverdue == other.isOverdue;
}
