// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'ledger.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `lock`, `outgoing`, `overview_from_state`, `unsigned`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`

/// Creates this device's identity with no group yet. `member_id` is the
/// identity every member of the group will see: use an opaque value, not a
/// name.
Future<Household> householdNew({
  required String memberId,
  required String reportingCurrencyCode,
}) => RustLib.instance.api.crateApiSharedHouseholdNew(
  memberId: memberId,
  reportingCurrencyCode: reportingCurrencyCode,
);

/// Restores a household from [`household_export`]'s bytes.
Future<Household> householdRestore({required List<int> saved}) =>
    RustLib.instance.api.crateApiSharedHouseholdRestore(saved: saved);

/// Import signed history from a backup after a replacement identity has joined
/// the original household. Old sender keys and delivery intent are not reused.
/// Returns false without importing while the old signing key is still a member.
Future<bool> householdMergeRecoveryHistory({
  required Household household,
  required List<int> saved,
}) => RustLib.instance.api.crateApiSharedHouseholdMergeRecoveryHistory(
  household: household,
  saved: saved,
);

/// Everything needed to resume after a restart, including private keys:
/// store it like a password. Includes an exact pending-commit journal.
Future<Uint8List> householdExport({required Household household}) =>
    RustLib.instance.api.crateApiSharedHouseholdExport(household: household);

/// A fresh single-use key package for someone to invite this device with.
/// Hand it to them out of band (never through the relay).
Future<Uint8List> householdKeyPackage({required Household household}) => RustLib
    .instance
    .api
    .crateApiSharedHouseholdKeyPackage(household: household);

/// Starts a new household with this device as its only member; returns the
/// group's random ID.
Future<String> householdFound({required Household household}) =>
    RustLib.instance.api.crateApiSharedHouseholdFound(household: household);

Future<void> householdJoin({
  required Household household,
  required String groupId,
  required List<int> welcome,
  required PlatformInt64 joinedAfter,
}) => RustLib.instance.api.crateApiSharedHouseholdJoin(
  household: household,
  groupId: groupId,
  welcome: welcome,
  joinedAfter: joinedAfter,
);

Future<StagedInvite> householdBeginInvite({
  required Household household,
  required List<int> keyPackage,
}) => RustLib.instance.api.crateApiSharedHouseholdBeginInvite(
  household: household,
  keyPackage: keyPackage,
);

Future<OutgoingEntry> householdBeginRemoval({
  required Household household,
  required String memberId,
}) => RustLib.instance.api.crateApiSharedHouseholdBeginRemoval(
  household: household,
  memberId: memberId,
);

Future<void> householdCommitAccepted({
  required Household household,
  required PlatformInt64 sequence,
}) => RustLib.instance.api.crateApiSharedHouseholdCommitAccepted(
  household: household,
  sequence: sequence,
);

Future<void> householdCommitRejected({required Household household}) => RustLib
    .instance
    .api
    .crateApiSharedHouseholdCommitRejected(household: household);

/// Processes relay entries in order (replays are skipped; a gap is an error).
Future<void> householdIngest({
  required Household household,
  required List<RelayEntry> entries,
}) => RustLib.instance.api.crateApiSharedHouseholdIngest(
  household: household,
  entries: entries,
);

/// The next queued event, encrypted, for Dart to append; `None` when the
/// outbox is empty. Returns the same event again until it is accepted.
Future<OutgoingEntry?> householdNextOutgoing({required Household household}) =>
    RustLib.instance.api.crateApiSharedHouseholdNextOutgoing(
      household: household,
    );

Future<void> householdOutgoingAccepted({
  required Household household,
  required PlatformInt64 sequence,
}) => RustLib.instance.api.crateApiSharedHouseholdOutgoingAccepted(
  household: household,
  sequence: sequence,
);

Future<void> householdOpenAccount({
  required Household household,
  required String accountId,
  required String name,
  required String currencyCode,
  required PlatformInt64 wallClockMillis,
}) => RustLib.instance.api.crateApiSharedHouseholdOpenAccount(
  household: household,
  accountId: accountId,
  name: name,
  currencyCode: currencyCode,
  wallClockMillis: wallClockMillis,
);

/// Records a shared expense or income. Like the personal ledger, the rate
/// freezes on the entry (`fx_numerator` / `fx_denominator`: reporting minor
/// units per source minor unit).
Future<void> householdRecordTransaction({
  required Household household,
  required String transactionId,
  required String accountId,
  required EntryKind kind,
  required String amount,
  required String currencyCode,
  required PlatformInt64 fxNumerator,
  required PlatformInt64 fxDenominator,
  required String title,
  String? categoryId,
  required PlatformInt64 wallClockMillis,
}) => RustLib.instance.api.crateApiSharedHouseholdRecordTransaction(
  household: household,
  transactionId: transactionId,
  accountId: accountId,
  kind: kind,
  amount: amount,
  currencyCode: currencyCode,
  fxNumerator: fxNumerator,
  fxDenominator: fxDenominator,
  title: title,
  categoryId: categoryId,
  wallClockMillis: wallClockMillis,
);

/// Changes an expense's amount. Two people doing this at once is a visible
/// conflict, not a silent overwrite.
Future<void> householdAdjustAmount({
  required Household household,
  required String transactionId,
  required String amount,
  required String currencyCode,
  required PlatformInt64 fxNumerator,
  required PlatformInt64 fxDenominator,
  required PlatformInt64 wallClockMillis,
}) => RustLib.instance.api.crateApiSharedHouseholdAdjustAmount(
  household: household,
  transactionId: transactionId,
  amount: amount,
  currencyCode: currencyCode,
  fxNumerator: fxNumerator,
  fxDenominator: fxDenominator,
  wallClockMillis: wallClockMillis,
);

Future<void> householdVoidTransaction({
  required Household household,
  required String transactionId,
  required PlatformInt64 wallClockMillis,
}) => RustLib.instance.api.crateApiSharedHouseholdVoidTransaction(
  household: household,
  transactionId: transactionId,
  wallClockMillis: wallClockMillis,
);

Future<HouseholdOverview> householdOverview({required Household household}) =>
    RustLib.instance.api.crateApiSharedHouseholdOverview(household: household);

/// The safety number shared between this device and `member_id`: read it
/// aloud or compare it on screen; if it differs on the two devices, someone
/// substituted a key.
Future<String> householdSafetyNumber({
  required Household household,
  required String memberId,
}) => RustLib.instance.api.crateApiSharedHouseholdSafetyNumber(
  household: household,
  memberId: memberId,
);

/// A new recovery phrase: 24 words to write down. Nothing is stored.
Future<String> recoveryGeneratePhrase() =>
    RustLib.instance.api.crateApiSharedRecoveryGeneratePhrase();

/// Checks that typed words are a valid phrase (right words, right order).
Future<void> recoveryValidatePhrase({required String phrase}) =>
    RustLib.instance.api.crateApiSharedRecoveryValidatePhrase(phrase: phrase);

/// Encrypts a device backup (for example [`household_export`]'s bytes) under
/// the phrase, for storage anywhere.
Future<Uint8List> recoverySeal({
  required String phrase,
  required List<int> plaintext,
}) => RustLib.instance.api.crateApiSharedRecoverySeal(
  phrase: phrase,
  plaintext: plaintext,
);

Future<Uint8List> recoveryOpen({
  required String phrase,
  required List<int> sealed,
}) => RustLib.instance.api.crateApiSharedRecoveryOpen(
  phrase: phrase,
  sealed: sealed,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Household>>
abstract class Household implements RustOpaqueInterface {}

/// Two concurrent edits of one expense: both stay visible.
class ConflictView {
  final String transactionId;
  final String overwrittenEventId;
  final String winningEventId;

  const ConflictView({
    required this.transactionId,
    required this.overwrittenEventId,
    required this.winningEventId,
  });

  @override
  int get hashCode =>
      transactionId.hashCode ^
      overwrittenEventId.hashCode ^
      winningEventId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConflictView &&
          runtimeType == other.runtimeType &&
          transactionId == other.transactionId &&
          overwrittenEventId == other.overwrittenEventId &&
          winningEventId == other.winningEventId;
}

class HouseholdOverview {
  final String memberId;
  final String? groupId;
  final bool isMember;

  /// Sequence number of the last relay entry processed.
  final PlatformInt64 cursor;

  /// Locally written events not yet sent to the relay.
  final PlatformInt64 pendingCount;
  final List<String> memberIds;
  final String balanceLabel;
  final List<AccountView> accounts;
  final List<SharedTransactionView> transactions;
  final List<ConflictView> conflicts;
  final List<RejectedView> rejected;

  const HouseholdOverview({
    required this.memberId,
    this.groupId,
    required this.isMember,
    required this.cursor,
    required this.pendingCount,
    required this.memberIds,
    required this.balanceLabel,
    required this.accounts,
    required this.transactions,
    required this.conflicts,
    required this.rejected,
  });

  @override
  int get hashCode =>
      memberId.hashCode ^
      groupId.hashCode ^
      isMember.hashCode ^
      cursor.hashCode ^
      pendingCount.hashCode ^
      memberIds.hashCode ^
      balanceLabel.hashCode ^
      accounts.hashCode ^
      transactions.hashCode ^
      conflicts.hashCode ^
      rejected.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HouseholdOverview &&
          runtimeType == other.runtimeType &&
          memberId == other.memberId &&
          groupId == other.groupId &&
          isMember == other.isMember &&
          cursor == other.cursor &&
          pendingCount == other.pendingCount &&
          memberIds == other.memberIds &&
          balanceLabel == other.balanceLabel &&
          accounts == other.accounts &&
          transactions == other.transactions &&
          conflicts == other.conflicts &&
          rejected == other.rejected;
}

/// Something for Dart to append to the relay log, only if the log's tail is
/// still `expected_tail`.
class OutgoingEntry {
  final PlatformInt64 expectedTail;
  final Uint8List blob;

  const OutgoingEntry({required this.expectedTail, required this.blob});

  @override
  int get hashCode => expectedTail.hashCode ^ blob.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OutgoingEntry &&
          runtimeType == other.runtimeType &&
          expectedTail == other.expectedTail &&
          blob == other.blob;
}

/// An event that could not apply (for example an edit of a voided expense).
class RejectedView {
  final String eventId;
  final String reason;

  const RejectedView({required this.eventId, required this.reason});

  @override
  int get hashCode => eventId.hashCode ^ reason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RejectedView &&
          runtimeType == other.runtimeType &&
          eventId == other.eventId &&
          reason == other.reason;
}

/// One entry of the relay's log, as fetched by Dart.
class RelayEntry {
  final PlatformInt64 sequence;
  final Uint8List blob;

  const RelayEntry({required this.sequence, required this.blob});

  @override
  int get hashCode => sequence.hashCode ^ blob.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RelayEntry &&
          runtimeType == other.runtimeType &&
          sequence == other.sequence &&
          blob == other.blob;
}

class SharedTransactionView {
  final String id;
  final String accountId;
  final String title;
  final String amountLabel;
  final bool isExpense;
  final bool voided;
  final String? categoryId;

  /// Two people edited this expense without seeing each other's edit.
  final bool conflicted;

  const SharedTransactionView({
    required this.id,
    required this.accountId,
    required this.title,
    required this.amountLabel,
    required this.isExpense,
    required this.voided,
    this.categoryId,
    required this.conflicted,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      accountId.hashCode ^
      title.hashCode ^
      amountLabel.hashCode ^
      isExpense.hashCode ^
      voided.hashCode ^
      categoryId.hashCode ^
      conflicted.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SharedTransactionView &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          accountId == other.accountId &&
          title == other.title &&
          amountLabel == other.amountLabel &&
          isExpense == other.isExpense &&
          voided == other.voided &&
          categoryId == other.categoryId &&
          conflicted == other.conflicted;
}

/// A staged commit that adds a member. `welcome` is for the new member and
/// must only be delivered (left in a mailbox) once the relay has accepted
/// `commit`.
class StagedInvite {
  final OutgoingEntry commit;
  final Uint8List welcome;

  const StagedInvite({required this.commit, required this.welcome});

  @override
  int get hashCode => commit.hashCode ^ welcome.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StagedInvite &&
          runtimeType == other.runtimeType &&
          commit == other.commit &&
          welcome == other.welcome;
}
