// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `step`

StorageResponse sqliteSerialized({
  required List<int> database,
  required StorageRequest request,
}) => RustLib.instance.api.crateApiStorageSqliteSerialized(
  database: database,
  request: request,
);

StorageResponse sqliteFile({
  required String path,
  required StorageRequest request,
}) => RustLib.instance.api.crateApiStorageSqliteFile(
  path: path,
  request: request,
);

enum StorageOperation {
  readDocument,
  writeDocument,
  openLog,
  appendFrame,
  recoverPrefix,
}

class StorageRequest {
  final String name;
  final StorageOperation operation;
  final PlatformInt64 expectedRevision;
  final Uint8List? value;
  final BigInt expectedLength;
  final BigInt validLength;

  const StorageRequest({
    required this.name,
    required this.operation,
    required this.expectedRevision,
    this.value,
    required this.expectedLength,
    required this.validLength,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      operation.hashCode ^
      expectedRevision.hashCode ^
      value.hashCode ^
      expectedLength.hashCode ^
      validLength.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StorageRequest &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          operation == other.operation &&
          expectedRevision == other.expectedRevision &&
          value == other.value &&
          expectedLength == other.expectedLength &&
          validLength == other.validLength;
}

class StorageResponse {
  final PlatformInt64 revision;
  final Uint8List? value;

  /// Empty for native files; web saves the complete SQLite image atomically.
  final Uint8List database;

  const StorageResponse({
    required this.revision,
    this.value,
    required this.database,
  });

  @override
  int get hashCode => revision.hashCode ^ value.hashCode ^ database.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StorageResponse &&
          runtimeType == other.runtimeType &&
          revision == other.revision &&
          value == other.value &&
          database == other.database;
}
