// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/budgets.dart';
import 'api/categories.dart';
import 'api/goals.dart';
import 'api/ledger.dart';
import 'api/recurring.dart';
import 'api/shared.dart';
import 'api/storage.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_BudgetBookPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBudgetBook;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_CategoryBookPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCategoryBook;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_GoalBookPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGoalBook;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_HouseholdPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHousehold;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_PersonalLedgerPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPersonalLedger;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_RecurringBookPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRecurringBook;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_SummaryDraftPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSummaryDraft;

  @protected
  BudgetBook
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBudgetBook(
    dynamic raw,
  );

  @protected
  CategoryBook
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCategoryBook(
    dynamic raw,
  );

  @protected
  GoalBook
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGoalBook(
    dynamic raw,
  );

  @protected
  Household
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHousehold(
    dynamic raw,
  );

  @protected
  PersonalLedger
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPersonalLedger(
    dynamic raw,
  );

  @protected
  RecurringBook
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRecurringBook(
    dynamic raw,
  );

  @protected
  SummaryDraft
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSummaryDraft(
    dynamic raw,
  );

  @protected
  BudgetBook
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBudgetBook(
    dynamic raw,
  );

  @protected
  CategoryBook
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCategoryBook(
    dynamic raw,
  );

  @protected
  GoalBook
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGoalBook(
    dynamic raw,
  );

  @protected
  Household
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHousehold(
    dynamic raw,
  );

  @protected
  PersonalLedger
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPersonalLedger(
    dynamic raw,
  );

  @protected
  RecurringBook
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRecurringBook(
    dynamic raw,
  );

  @protected
  SummaryDraft
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSummaryDraft(
    dynamic raw,
  );

  @protected
  BudgetBook
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBudgetBook(
    dynamic raw,
  );

  @protected
  CategoryBook
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCategoryBook(
    dynamic raw,
  );

  @protected
  GoalBook
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGoalBook(
    dynamic raw,
  );

  @protected
  Household
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHousehold(
    dynamic raw,
  );

  @protected
  PersonalLedger
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPersonalLedger(
    dynamic raw,
  );

  @protected
  RecurringBook
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRecurringBook(
    dynamic raw,
  );

  @protected
  SummaryDraft
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSummaryDraft(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AccountView dco_decode_account_view(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  OutgoingEntry dco_decode_box_autoadd_outgoing_entry(dynamic raw);

  @protected
  StorageRequest dco_decode_box_autoadd_storage_request(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BudgetLoadReport dco_decode_budget_load_report(dynamic raw);

  @protected
  BudgetMutation dco_decode_budget_mutation(dynamic raw);

  @protected
  BudgetPeriodKind dco_decode_budget_period_kind(dynamic raw);

  @protected
  BudgetView dco_decode_budget_view(dynamic raw);

  @protected
  CategoryLoadReport dco_decode_category_load_report(dynamic raw);

  @protected
  CategoryMutation dco_decode_category_mutation(dynamic raw);

  @protected
  CategoryView dco_decode_category_view(dynamic raw);

  @protected
  ConflictView dco_decode_conflict_view(dynamic raw);

  @protected
  EntryKind dco_decode_entry_kind(dynamic raw);

  @protected
  FxRatio dco_decode_fx_ratio(dynamic raw);

  @protected
  GoalKind dco_decode_goal_kind(dynamic raw);

  @protected
  GoalLoadReport dco_decode_goal_load_report(dynamic raw);

  @protected
  GoalMutation dco_decode_goal_mutation(dynamic raw);

  @protected
  GoalView dco_decode_goal_view(dynamic raw);

  @protected
  HouseholdOverview dco_decode_household_overview(dynamic raw);

  @protected
  HouseholdRequestProof dco_decode_household_request_proof(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  LedgerMutation dco_decode_ledger_mutation(dynamic raw);

  @protected
  LedgerOverview dco_decode_ledger_overview(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AccountView> dco_decode_list_account_view(dynamic raw);

  @protected
  List<BudgetView> dco_decode_list_budget_view(dynamic raw);

  @protected
  List<CategoryView> dco_decode_list_category_view(dynamic raw);

  @protected
  List<ConflictView> dco_decode_list_conflict_view(dynamic raw);

  @protected
  List<GoalView> dco_decode_list_goal_view(dynamic raw);

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<PublishedSummaryView> dco_decode_list_published_summary_view(
    dynamic raw,
  );

  @protected
  List<RejectedView> dco_decode_list_rejected_view(dynamic raw);

  @protected
  List<RelayEntry> dco_decode_list_relay_entry(dynamic raw);

  @protected
  List<SharedTransactionView> dco_decode_list_shared_transaction_view(
    dynamic raw,
  );

  @protected
  List<TransactionHistoryView> dco_decode_list_transaction_history_view(
    dynamic raw,
  );

  @protected
  List<TransactionView> dco_decode_list_transaction_view(dynamic raw);

  @protected
  List<TransferView> dco_decode_list_transfer_view(dynamic raw);

  @protected
  List<UpcomingView> dco_decode_list_upcoming_view(dynamic raw);

  @protected
  LoadReport dco_decode_load_report(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  OutgoingEntry? dco_decode_opt_box_autoadd_outgoing_entry(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  OutgoingEntry dco_decode_outgoing_entry(dynamic raw);

  @protected
  PublishedSummaryView dco_decode_published_summary_view(dynamic raw);

  @protected
  RecurringFrequency dco_decode_recurring_frequency(dynamic raw);

  @protected
  RecurringKind dco_decode_recurring_kind(dynamic raw);

  @protected
  RecurringLoadReport dco_decode_recurring_load_report(dynamic raw);

  @protected
  RecurringMutation dco_decode_recurring_mutation(dynamic raw);

  @protected
  RejectedView dco_decode_rejected_view(dynamic raw);

  @protected
  RelayEntry dco_decode_relay_entry(dynamic raw);

  @protected
  SharedTransactionView dco_decode_shared_transaction_view(dynamic raw);

  @protected
  StagedInvite dco_decode_staged_invite(dynamic raw);

  @protected
  StorageOperation dco_decode_storage_operation(dynamic raw);

  @protected
  StorageRequest dco_decode_storage_request(dynamic raw);

  @protected
  StorageResponse dco_decode_storage_response(dynamic raw);

  @protected
  SummaryPreview dco_decode_summary_preview(dynamic raw);

  @protected
  TransactionHistoryView dco_decode_transaction_history_view(dynamic raw);

  @protected
  TransactionView dco_decode_transaction_view(dynamic raw);

  @protected
  TransferView dco_decode_transfer_view(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UpcomingView dco_decode_upcoming_view(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  BudgetBook
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBudgetBook(
    SseDeserializer deserializer,
  );

  @protected
  CategoryBook
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCategoryBook(
    SseDeserializer deserializer,
  );

  @protected
  GoalBook
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGoalBook(
    SseDeserializer deserializer,
  );

  @protected
  Household
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHousehold(
    SseDeserializer deserializer,
  );

  @protected
  PersonalLedger
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPersonalLedger(
    SseDeserializer deserializer,
  );

  @protected
  RecurringBook
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRecurringBook(
    SseDeserializer deserializer,
  );

  @protected
  SummaryDraft
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSummaryDraft(
    SseDeserializer deserializer,
  );

  @protected
  BudgetBook
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBudgetBook(
    SseDeserializer deserializer,
  );

  @protected
  CategoryBook
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCategoryBook(
    SseDeserializer deserializer,
  );

  @protected
  GoalBook
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGoalBook(
    SseDeserializer deserializer,
  );

  @protected
  Household
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHousehold(
    SseDeserializer deserializer,
  );

  @protected
  PersonalLedger
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPersonalLedger(
    SseDeserializer deserializer,
  );

  @protected
  RecurringBook
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRecurringBook(
    SseDeserializer deserializer,
  );

  @protected
  SummaryDraft
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSummaryDraft(
    SseDeserializer deserializer,
  );

  @protected
  BudgetBook
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBudgetBook(
    SseDeserializer deserializer,
  );

  @protected
  CategoryBook
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCategoryBook(
    SseDeserializer deserializer,
  );

  @protected
  GoalBook
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGoalBook(
    SseDeserializer deserializer,
  );

  @protected
  Household
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHousehold(
    SseDeserializer deserializer,
  );

  @protected
  PersonalLedger
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPersonalLedger(
    SseDeserializer deserializer,
  );

  @protected
  RecurringBook
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRecurringBook(
    SseDeserializer deserializer,
  );

  @protected
  SummaryDraft
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSummaryDraft(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AccountView sse_decode_account_view(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  OutgoingEntry sse_decode_box_autoadd_outgoing_entry(
    SseDeserializer deserializer,
  );

  @protected
  StorageRequest sse_decode_box_autoadd_storage_request(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BudgetLoadReport sse_decode_budget_load_report(SseDeserializer deserializer);

  @protected
  BudgetMutation sse_decode_budget_mutation(SseDeserializer deserializer);

  @protected
  BudgetPeriodKind sse_decode_budget_period_kind(SseDeserializer deserializer);

  @protected
  BudgetView sse_decode_budget_view(SseDeserializer deserializer);

  @protected
  CategoryLoadReport sse_decode_category_load_report(
    SseDeserializer deserializer,
  );

  @protected
  CategoryMutation sse_decode_category_mutation(SseDeserializer deserializer);

  @protected
  CategoryView sse_decode_category_view(SseDeserializer deserializer);

  @protected
  ConflictView sse_decode_conflict_view(SseDeserializer deserializer);

  @protected
  EntryKind sse_decode_entry_kind(SseDeserializer deserializer);

  @protected
  FxRatio sse_decode_fx_ratio(SseDeserializer deserializer);

  @protected
  GoalKind sse_decode_goal_kind(SseDeserializer deserializer);

  @protected
  GoalLoadReport sse_decode_goal_load_report(SseDeserializer deserializer);

  @protected
  GoalMutation sse_decode_goal_mutation(SseDeserializer deserializer);

  @protected
  GoalView sse_decode_goal_view(SseDeserializer deserializer);

  @protected
  HouseholdOverview sse_decode_household_overview(SseDeserializer deserializer);

  @protected
  HouseholdRequestProof sse_decode_household_request_proof(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  LedgerMutation sse_decode_ledger_mutation(SseDeserializer deserializer);

  @protected
  LedgerOverview sse_decode_ledger_overview(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AccountView> sse_decode_list_account_view(SseDeserializer deserializer);

  @protected
  List<BudgetView> sse_decode_list_budget_view(SseDeserializer deserializer);

  @protected
  List<CategoryView> sse_decode_list_category_view(
    SseDeserializer deserializer,
  );

  @protected
  List<ConflictView> sse_decode_list_conflict_view(
    SseDeserializer deserializer,
  );

  @protected
  List<GoalView> sse_decode_list_goal_view(SseDeserializer deserializer);

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(
    SseDeserializer deserializer,
  );

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<PublishedSummaryView> sse_decode_list_published_summary_view(
    SseDeserializer deserializer,
  );

  @protected
  List<RejectedView> sse_decode_list_rejected_view(
    SseDeserializer deserializer,
  );

  @protected
  List<RelayEntry> sse_decode_list_relay_entry(SseDeserializer deserializer);

  @protected
  List<SharedTransactionView> sse_decode_list_shared_transaction_view(
    SseDeserializer deserializer,
  );

  @protected
  List<TransactionHistoryView> sse_decode_list_transaction_history_view(
    SseDeserializer deserializer,
  );

  @protected
  List<TransactionView> sse_decode_list_transaction_view(
    SseDeserializer deserializer,
  );

  @protected
  List<TransferView> sse_decode_list_transfer_view(
    SseDeserializer deserializer,
  );

  @protected
  List<UpcomingView> sse_decode_list_upcoming_view(
    SseDeserializer deserializer,
  );

  @protected
  LoadReport sse_decode_load_report(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  OutgoingEntry? sse_decode_opt_box_autoadd_outgoing_entry(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  OutgoingEntry sse_decode_outgoing_entry(SseDeserializer deserializer);

  @protected
  PublishedSummaryView sse_decode_published_summary_view(
    SseDeserializer deserializer,
  );

  @protected
  RecurringFrequency sse_decode_recurring_frequency(
    SseDeserializer deserializer,
  );

  @protected
  RecurringKind sse_decode_recurring_kind(SseDeserializer deserializer);

  @protected
  RecurringLoadReport sse_decode_recurring_load_report(
    SseDeserializer deserializer,
  );

  @protected
  RecurringMutation sse_decode_recurring_mutation(SseDeserializer deserializer);

  @protected
  RejectedView sse_decode_rejected_view(SseDeserializer deserializer);

  @protected
  RelayEntry sse_decode_relay_entry(SseDeserializer deserializer);

  @protected
  SharedTransactionView sse_decode_shared_transaction_view(
    SseDeserializer deserializer,
  );

  @protected
  StagedInvite sse_decode_staged_invite(SseDeserializer deserializer);

  @protected
  StorageOperation sse_decode_storage_operation(SseDeserializer deserializer);

  @protected
  StorageRequest sse_decode_storage_request(SseDeserializer deserializer);

  @protected
  StorageResponse sse_decode_storage_response(SseDeserializer deserializer);

  @protected
  SummaryPreview sse_decode_summary_preview(SseDeserializer deserializer);

  @protected
  TransactionHistoryView sse_decode_transaction_history_view(
    SseDeserializer deserializer,
  );

  @protected
  TransactionView sse_decode_transaction_view(SseDeserializer deserializer);

  @protected
  TransferView sse_decode_transfer_view(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UpcomingView sse_decode_upcoming_view(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBudgetBook(
    BudgetBook self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCategoryBook(
    CategoryBook self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGoalBook(
    GoalBook self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHousehold(
    Household self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPersonalLedger(
    PersonalLedger self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRecurringBook(
    RecurringBook self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSummaryDraft(
    SummaryDraft self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBudgetBook(
    BudgetBook self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCategoryBook(
    CategoryBook self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGoalBook(
    GoalBook self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHousehold(
    Household self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPersonalLedger(
    PersonalLedger self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRecurringBook(
    RecurringBook self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSummaryDraft(
    SummaryDraft self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBudgetBook(
    BudgetBook self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCategoryBook(
    CategoryBook self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGoalBook(
    GoalBook self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHousehold(
    Household self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPersonalLedger(
    PersonalLedger self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRecurringBook(
    RecurringBook self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSummaryDraft(
    SummaryDraft self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_account_view(AccountView self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_outgoing_entry(
    OutgoingEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_storage_request(
    StorageRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_budget_load_report(
    BudgetLoadReport self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_budget_mutation(
    BudgetMutation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_budget_period_kind(
    BudgetPeriodKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_budget_view(BudgetView self, SseSerializer serializer);

  @protected
  void sse_encode_category_load_report(
    CategoryLoadReport self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_category_mutation(
    CategoryMutation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_category_view(CategoryView self, SseSerializer serializer);

  @protected
  void sse_encode_conflict_view(ConflictView self, SseSerializer serializer);

  @protected
  void sse_encode_entry_kind(EntryKind self, SseSerializer serializer);

  @protected
  void sse_encode_fx_ratio(FxRatio self, SseSerializer serializer);

  @protected
  void sse_encode_goal_kind(GoalKind self, SseSerializer serializer);

  @protected
  void sse_encode_goal_load_report(
    GoalLoadReport self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_goal_mutation(GoalMutation self, SseSerializer serializer);

  @protected
  void sse_encode_goal_view(GoalView self, SseSerializer serializer);

  @protected
  void sse_encode_household_overview(
    HouseholdOverview self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_household_request_proof(
    HouseholdRequestProof self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_ledger_mutation(
    LedgerMutation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ledger_overview(
    LedgerOverview self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_account_view(
    List<AccountView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_budget_view(
    List<BudgetView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_category_view(
    List<CategoryView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_conflict_view(
    List<ConflictView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_goal_view(List<GoalView> self, SseSerializer serializer);

  @protected
  void sse_encode_list_list_prim_u_8_strict(
    List<Uint8List> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_published_summary_view(
    List<PublishedSummaryView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_rejected_view(
    List<RejectedView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_relay_entry(
    List<RelayEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_shared_transaction_view(
    List<SharedTransactionView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_transaction_history_view(
    List<TransactionHistoryView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_transaction_view(
    List<TransactionView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_transfer_view(
    List<TransferView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_upcoming_view(
    List<UpcomingView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_load_report(LoadReport self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_outgoing_entry(
    OutgoingEntry? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_outgoing_entry(OutgoingEntry self, SseSerializer serializer);

  @protected
  void sse_encode_published_summary_view(
    PublishedSummaryView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_recurring_frequency(
    RecurringFrequency self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_recurring_kind(RecurringKind self, SseSerializer serializer);

  @protected
  void sse_encode_recurring_load_report(
    RecurringLoadReport self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_recurring_mutation(
    RecurringMutation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rejected_view(RejectedView self, SseSerializer serializer);

  @protected
  void sse_encode_relay_entry(RelayEntry self, SseSerializer serializer);

  @protected
  void sse_encode_shared_transaction_view(
    SharedTransactionView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_staged_invite(StagedInvite self, SseSerializer serializer);

  @protected
  void sse_encode_storage_operation(
    StorageOperation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_storage_request(
    StorageRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_storage_response(
    StorageResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_summary_preview(
    SummaryPreview self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_transaction_history_view(
    TransactionHistoryView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_transaction_view(
    TransactionView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_transfer_view(TransferView self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_upcoming_view(UpcomingView self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBudgetBook(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBudgetBook(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBudgetBook(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBudgetBook(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCategoryBook(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCategoryBook(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCategoryBook(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCategoryBook(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGoalBook(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGoalBook(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGoalBook(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGoalBook(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHousehold(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHousehold(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHousehold(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHousehold(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPersonalLedger(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPersonalLedger(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPersonalLedger(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPersonalLedger(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRecurringBook(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRecurringBook(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRecurringBook(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRecurringBook(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSummaryDraft(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSummaryDraft(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSummaryDraft(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSummaryDraft(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBudgetBook(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBudgetBook(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCategoryBook(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCategoryBook(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGoalBook(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGoalBook(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHousehold(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHousehold(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPersonalLedger(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPersonalLedger(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRecurringBook(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRecurringBook(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSummaryDraft(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSummaryDraft(
    int ptr,
  );
}
